---
- name: Get bashrc_file variable
  include_role:
    name: read-files
  vars:
    bashrc_file: "{{ bashrc_file }}"

- name: basic bash config
  when: bashrc_file.stdout.find('##Basic configs') == -1
  blockinfile:
    dest: "{{ user_home }}/.bashrc"
    marker: "##Basic configs"
    block: |
       stty -ixon # Disable ctrl-s and ctrl-q.
       shopt -s autocd #Allows you to cd into directory merely by typing the directory name.
       HISTSIZE= HISTFILESIZE= # Infinite history.
       export PS1="\[$(tput bold)\]\[$(tput setaf 1)\][\[$(tput setaf 3)\]\u\[$(tput setaf 2)\]@\[$(tput setaf 4)\]\h \[$(tput setaf 5)\]\W\[$(tput setaf 1)\]]\[$(tput setaf 7)\]\\$ \[$(tput sgr0)\]"
       
       [ -f "$HOME/.config/shortcutrc" ] && source "$HOME/.config/shortcutrc" # Load shortcut aliases
       [ -f "$HOME/.config/aliasrc" ] && source "$HOME/.config/aliasrc"
       
       alias ls='ls --color'
       export LS_COLORS='di=1;35:fi=0:ln=31:pi=5:so=5:bd=5:cd=5:or=31:mi=0:ex=35:*.rpm=90:*.png=35:*.gif=36:*.jpg=35:*.c=92:*.jar=33:*.py=93:*.h=90:*.txt=94:*.doc=104:*.docx=104:*.odt=104:*.csv=102:*.xlsx=102:*.xlsm=102:*.rb=31:*.cpp=92:*.sh=92:*.html=96:*.zip=4;33:*.tar.gz=4;33:*.mp4=105:*.mp3=106'
       
- name: Install tmux
  dnf:
    name: tmux
    state: latest

- name: install fzf
  dnf:
    name: fzf
    enablerepo: ripgrep
    state: latest

- name: Update bashrc file with fzf keybinds
  when: bashrc_file.stdout.find('##FZF mappings and options') == -1
  blockinfile:
    dest: "{{ user_home }}/.bashrc"
    marker: "##FZF mappings and options"
    block: |
       [ -f /usr/share/fzf/shell/key-bindings.bash ] && source /usr/share/fzf/shell/key-bindings.bash
       export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
       export FZF_DEFAULT_OPTS="--height 50% -1 --layout=reverse-list --multi --preview='[[ \$(file --mime {}) =~ binary ]] && echo {} is a binary file || (bat --style=numbers --color=always {} || cat {}) 2> /dev/null | head -300'"

