---
- name: download winetricks
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
    dest: /usr/local/bin/
    mode: '0755'

- name: Creates gu directory
  file:
    path: "{{ user_home }}/.gu"
    state: directory
    owner: "{{ lookup('env', 'USERNAME') }}"

- name: Build wine prefix
  become: yes
  become_user: "{{ lookup('env', 'USERNAME') }}"
  shell: "WINEPREFIX={{ user_home }}/.gu winecfg"

- name: Fix fonts
  become: yes
  become_user: "{{ lookup('env', 'USERNAME') }}"
  shell: "WINEPREFIX={{ user_home }}/.gu winetricks corefonts"

- name: Download dxvk
  become: yes
  become_user: "{{ lookup('env', 'USERNAME') }}"
  get_url:
    url: https://github.com/doitsujin/dxvk/releases/download/v1.10.1/dxvk-1.10.1.tar.gz
    dest: "{{ user_home }}"

- name: Untar dxkv
  become: yes
  become_user: "{{ lookup('env', 'USERNAME') }}"
  unarchive:
    src: "{{ user_home }}/dxvk-1.10.1.tar.gz"
    dest: "{{ user_home }}"

- name: Make 3d rendering work
  become: yes
  become_user: "{{ lookup('env', 'USERNAME') }}"
  shell: "WINEPREFIX={{ user_home }}/.gu {{ user_home }}/dxvk-1.10.1/setup_dxvk.sh install"

- name: Remove tmp files
  become: yes
  become_user: "{{ lookup('env', 'USERNAME') }}"
  shell: "rm {{ user_home }}/dxvk-1.10.1.tar.gz"

- name: Download GodsUnchained installer
  become: yes
  become_user: "{{ lookup('env', 'USERNAME') }}"
  get_url:
    url: https://downloads.immutable.com/Immutable+Setup+0.11.0.exe
    dest: "{{ user_home }}/Downloads"

- name: Install GU
  become: yes
  become_user: "{{ lookup('env', 'USERNAME') }}"
  shell: "WINEPREFIX={{ user_home}}/.gu wine {{ user_home }}/Downloads/Immutable+Setup+0.11.0.exe"

- name: Get icon name
  become: yes
  become_user: "{{ lookup('env', 'USERNAME') }}"
  shell: cat Immutable.desktop | grep Icon
  args:
    chdir: "{{ user_home}}/.local/share/applications/wine/Programs"
  register: icon_line
  ignore_errors: yes

- name: Copy desktop file
  become: yes
  become_user: "{{ lookup('env', 'USERNAME') }}"
  ansible.builtin.copy:
    dest: "{{ user_home }}/.local/share/applications/wine/Programs/gu.desktop"
    content: |
      [Desktop Entry]
      Name=Gods Unchained
      Exec="{{ user_home }}/.local/share/applications/wine/Programs/godsunchained.sh"
      {{ icon_line.stdout }}
      Type=Application
      Categories=Game
      Terminal=false

- name: Create the script to exec gu
  become: yes
  become_user: "{{ lookup('env', 'USERNAME') }}"
  ansible.builtin.copy:
    dest: "{{ user_home }}/godsunchained.sh"
    content: |
        #! /bin/bash
        WINEPREFIX={{ user_home }}/.gu wine {{ user_home }}/.gu/drive_c/users/{{ lookup('env', 'USERNAME') }}/AppData/Local/Programs/immutable-launcher/Immutable.exe
    mode: '0755'


