---
#- name: Enable the RPM Fusion repository
#  dnf:
#    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-36.noarch.rpm"
#    state: present

- name: Enable AppStream metadata
  dnf:
    name: '@core'
    state: present

- name: install multimedia post-install
  dnf:
    name: '@multimedia'
    state: present
